mynewsdesk/mnd-bootstrap

Gemfile, Gemfile.lock, README.markdown, bin/setup, gulpfile.js
* Setup script which installs ruby, npm, gems, bower and gulp.
* Move gem dependencies to Gemfile so you can install them via `bundle`.
* Fix for the issue with the webserver failing on first run.
=> Setup dependencies

src/mnd-bootstrap/_variables.scss, src/mnd-bootstrap/css/_buttons.scss
- based on link-button but with no link behavior
- used for cancelations etc.
=> Secondary button

src/mnd-bootstrap/components/_content_list.scss
Minor tweak. Narrower margins.
=> Adjust paddings on content list component

src/mnd-bootstrap/_helpers.scss
Add class to align text depending on screen size
=> Responsive text alignment classes

dist/mnd-bootstrap.css, src/mnd-bootstrap/css/_forms.scss
=> Include panel in documentation around forms (Form heading)

dist/mnd-bootstrap.css, src/mnd-bootstrap/css/_forms.scss
This fixes padding on links used as secondary actions on forms. It supports multiple links. The links aren't floated by default but it works if you add .pull-* to your links.
=> Styles for form links

dist/mnd-bootstrap.css, src/mnd-bootstrap/components/_jumbotron.scss
=> Fixed padding and header weight on jumbotron

src/mnd-bootstrap/_variables_custom.scss
=> Include new gutter variables in docs

dist/mnd-bootstrap.css, src/mnd-bootstrap/_variables_custom.scss, src/mnd-bootstrap/javascript/_modal.scss
Style the actions buttons in the footer:
=> Style the modal footer actions

dist/mnd-bootstrap.css, src/mnd-bootstrap/components/_alerts.scss
=> Fix the positioning of the close button in dismissable alerts

dist/mnd-bootstrap.css, src/mnd-bootstrap/javascript/_modal.scss
=> Style for the icon in the modal header

dist/mnd-bootstrap.css, src/mnd-bootstrap/_variables.scss, src/mnd-bootstrap/components/_alerts.scss, src/mnd-bootstrap/components/_labels.scss
Moved the styling for labels from alerts into it's own component so they can be used in other places.
=> Add label component

bower.json, doc_assets/styleguide.scss, hologram_config.yml
Each project is responsible for importing FontAwesome.
=> Add fontawesome to styleguide.scss

dist/mnd-bootstrap.css, src/mnd-bootstrap.scss, src/mnd-bootstrap/javascript/_takeover.scss
=> Added takeover

src/mnd-bootstrap-dev.scss, src/mnd-bootstrap.scss
From what we can see these imports aren't needed, any input?
=> These imports aren't used

dist/mnd-bootstrap.css, src/mnd-bootstrap/_helpers.scss, src/mnd-bootstrap/components/_content_list.scss
Remove right aligned as default in content_list.
http://cl.ly/e0P6
=> Remove right aligned columns in content_list.

dist/mnd-bootstrap.css, src/mnd-bootstrap/_variables.scss
Switch colors for warning and danger as they are inverted.
=> Switch brand colors (warning and danger)

dist/mnd-bootstrap.css, src/mnd-bootstrap/components/_content_list.scss
=> Style btn-link as regular links in ContentList

dist/mnd-bootstrap.css, src/mnd-bootstrap/javascript/_takeover.scss
Set max-width to $container-md (970px) if the screensize is above $container-md
=> Adding max-width to takeover wide class

dist/mnd-bootstrap.css, src/mnd-bootstrap/javascript/_takeover.scss
* The `.wide` class should be the one setting `max-width: 100%`
If someone knows why some colors have changed, please let me know! :smile:
=> Change default Takeover width to be $container-md

dist/mnd-bootstrap.css, src/mnd-bootstrap/css/_buttons.scss
Fixed the documentation and added condition for when an <i> tag is present inside a small button
=> Fix buttons with icons

dist/mnd-bootstrap.css, src/mnd-bootstrap.scss, src/mnd-bootstrap/components/_avatar.scss, src/mnd-bootstrap/components/_button_dropdowns.scss, src/mnd-bootstrap/components/_content_list.scss, src/mnd-bootstrap/javascript/_modal.scss
* Fix padding from items in a DropdownButton
* Fix padding in Modal for mobile
* Extract padding for content-list-item to variable
=> Add class for Avatars

dist/mnd-bootstrap.css, src/mnd-bootstrap/components/_button_dropdowns.scss
The dropdown arrow was not aligned with the arrow button, now it is
=> Add padding to get the dropdown aligned correctly

dist/mnd-bootstrap.css, src/mnd-bootstrap/components/_wells.scss
We didn't have well in our documentation and the background was somewhat grey.
=> Add Wells into documentation since we use them

dist/mnd-bootstrap.css, src/mnd-bootstrap/css/_buttons.scss, src/mnd-bootstrap/css/_forms.scss, src/mnd-bootstrap/variables/_colors.scss
New! - redesign input button combo
New! - added locked field, use instead of disabled field
Updated! - changed brand color to green (brand-success color)
=> New version including account-setup design elements

dist/mnd-bootstrap.css, src/mnd-bootstrap/components/_button_dropdowns.scss
=> Add box-shadow to dropdowns

dist/mnd-bootstrap.css, src/mnd-bootstrap/components/_button_groups.scss, src/mnd-bootstrap/css/_forms.scss, src/mnd-bootstrap/variables/_buttons.scss, src/mnd-bootstrap/variables/_forms.scss
=> Better alignment of form elements and text

dist/mnd-bootstrap.css, src/mnd-bootstrap-dev.scss, src/mnd-bootstrap.scss, src/mnd-bootstrap/css/_scaffoldings.scss
- To make it more aligned with the rest of the margins we go for this change
=> Added documentation and specific CSS for HR

dist/mnd-bootstrap.css, src/mnd-bootstrap/javascript/_modal.scss, src/mnd-bootstrap/javascript/_takeover.scss, src/mnd-bootstrap/variables/_measures.scss
=> Add a margin-top to modals on desktop

dist/mnd-bootstrap.css, src/mnd-bootstrap/components/_labels.scss
Included larger version of labels
=> Make it possible to use large labels

dist/mnd-bootstrap.css, src/mnd-bootstrap/css/_buttons.scss, src/mnd-bootstrap/css/_buttons_social.scss
Need to have a more precise selector to get the styling we want on the social buttons.
=> React bootstrap automatically adds btn-default

dist/mnd-bootstrap.css, src/mnd-bootstrap/css/_buttons.scss
=> Remove left margin from first button

dist/mnd-bootstrap.css, src/mnd-bootstrap/css/_buttons.scss
Use default disable state for buttons
=> Use default cursor for button disable state

dist/mnd-bootstrap.css, src/mnd-bootstrap/javascript/_modal.scss
Make it possible to use good looking icons in modal header
=> Icons in header

dist/mnd-bootstrap.css, src/mnd-bootstrap/javascript/_modal.scss
Patch for better control inside header modal header
=> Include margin on modal header elements

package.json
=> Update NPM packages

gulpfile.js, package.json
- Remove rails assets task
- Use exact versions in package.json
=> Remove rails assets task

package.json
- bootstrap sass 3.3.6
- bourbon 4.2.7
=> Specify versions

dist/mnd-bootstrap.css, src/mnd-bootstrap/javascript/_modal.scss
=> Form group support in modal

dist/mnd-bootstrap.css, src/mnd-bootstrap/variables/_typography.scss
=> Make sure small text in h1 headings look great

dist/mnd-bootstrap.css, src/mnd-bootstrap/javascript/_modal.scss
=> Buttons needs margin on smaller screens

dist/mnd-bootstrap.css, src/mnd-bootstrap/javascript/_modal.scss
=> Vertical aligned modals

dist/mnd-bootstrap.css, src/mnd-bootstrap/javascript/_modal.scss
This solves the visible scrollbars on some browsers like IE, Edge
=> Hide scrollbars

dist/mnd-bootstrap.css, src/mnd-bootstrap/components/_scoreboard.scss
=> Update the styling of the Scoreboard component

dist/mnd-bootstrap.css, src/mnd-bootstrap/components/_button_groups.scss
=> Left align text in a vertical button group

dist/mnd-bootstrap.css, src/mnd-bootstrap/javascript/_modal.scss, src/mnd-bootstrap/variables/_typography.scss
=> Increase font size for font-size-small. Add smaller font size. 

dist/mnd-bootstrap.css, src/mnd-bootstrap/variables/_buttons.scss
=> Change focus color on buttons to dark grey (from grey blue)

dist/mnd-bootstrap.css, src/mnd-bootstrap/variables/_measures.scss
=> Reduce horizontal padding in input fields

dist/mnd-bootstrap.css, src/mnd-bootstrap/components/_avatar.scss
There is an issue where the `Avatar` component jumps a bit the first
time you enter a character into it.
By adding this class we can have a character in the component always and
"hide" it preventing it from jumping.
=> Add class which set text color to background color

dist/mnd-bootstrap.css, src/mnd-bootstrap/components/_avatar.scss
=> Make empty avatars gray

dist/mnd-bootstrap.css, src/mnd-bootstrap/components/_content_list.scss
Add compact version of content-list
=> Refactor content-list to use new guidelines

dist/mnd-bootstrap.css, src/mnd-bootstrap/components/_content_list.scss
ContentList previously didn't show some columns. To make it work in different situations control this with specific visibility classes instead.
=> Hide columns in ColumnList with visitbility classes instead

bin/update
Since mmdx-dev run bin/update for every app we want it to do the same for mnd-bootstrap.
=> Make it compatible with mndx-dev

dist/mnd-bootstrap.css, src/mnd-bootstrap/components/_navs.scss, src/mnd-bootstrap/variables/_colors.scss
=> Update style of tab bar navigation component
